### ISSUE TITLE
issue-1-view-agent-list

### ISSUE THREAD

**Issue by jeff-cruz** [jeff-cruz/valorant-comp-builder#1]
## 💰 Motivation

User can view a list of Valorant agents.

## 📐 Plan

Create a list displaying all Valorant agents.

## 🖼️ Wireframes

<img width="316" alt="Screen Shot 2022-04-19 at 10 55 57 AM" src="https://user-images.githubusercontent.com/99565410/164066207-9118efa1-3c6b-4527-9e41-8707453c6371.png">

<img width="975" alt="Screen Shot 2022-04-19 at 11 15 50 AM" src="https://user-images.githubusercontent.com/99565410/164069283-4dbba367-1052-4c11-aa87-5357424ede30.png">

## ✅ Task List

- [x] Create HTML & CSS 
- [x] Obtain icon of a Valorant agent from the API
- [x] Append icon to list
- [x] Repeat until all agents are on the list 
- [x] Ensure that the page is mobile-responsive
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
