### ISSUE TITLE
issue-2-view-agent-details

### ISSUE THREAD

**Issue by jeff-cruz** [jeff-cruz/valorant-comp-builder#2]
## 💰 Motivation

User can view specific agents, their biography and their abilities.

## 📐 Plan

Create a list displaying the agent, along with their details.

## 🖼️ Wireframes

<img width="783" alt="Screen Shot 2022-04-20 at 11 20 16 AM" src="https://user-images.githubusercontent.com/99565410/164297007-dedc630e-5aaf-4b08-a2f4-bd8668dc00e8.png">
<img width="1004" alt="Screen Shot 2022-04-20 at 11 20 50 AM" src="https://user-images.githubusercontent.com/99565410/164296994-90a39c54-b8f3-4d8e-acbb-f3ce7ff956ae.png">

## ✅ Task List
- [x] Create HTML & CSS for agent bio/abilities
- [x] Add an event listener once an icon of an agent is clicked to show agent details
- [x] Get following info from API: 
    - [x] data ->displayName (agent name)
    - [x] data -> role -> displayName (agent role)
    - [x] data -> fullPortraitv2 (agent picture)
    - [x] data -> description (agent bio)
    - [x] data -> abilities -> displayIcon (ability image)
    - [x] data -> abilities -> displayName (ability name)
    - [x] data -> abilities -> description (ability info)
- [x] Append each to their respective sections in the HTML
- [x] Ensure that user can go back to the agent list page 
- [x] Ensure that the page is mobile-responsive
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
