### ISSUE TITLE
issue-3-create-comp

### ISSUE THREAD

**Issue by jeff-cruz** [jeff-cruz/valorant-comp-builder#3]
## 💰 Motivation

User can make their own team compositions.

## 📐 Plan

Create a team comp selection that is able to be saved.

## 🖼️ Wireframes

<img width="786" alt="Screen Shot 2022-04-20 at 5 34 14 PM" src="https://user-images.githubusercontent.com/99565410/164346886-afc4b3d8-73ed-4632-8307-d892b75da4ed.png">
<img width="986" alt="Screen Shot 2022-04-20 at 5 33 18 PM" src="https://user-images.githubusercontent.com/99565410/164346914-e898333a-84a2-43d0-9650-1f5b421d8381.png">

## ✅ Task List
- [x] Create button named "+Create Comp" to view swap to comp selection screen
- [x]  Create HTML and CSS for comp selection screen
- [x] Create an empty array in the data object named "agentComps" to store agent composition if selected
- [x] Add event listener to agent icons
    - [x] If agent icon is clicked, append that icon to comp selector box
    - [x] If agent icon is clicked inside the comp selector box, remove agent icon from comp selector box
- [x] Create a submit button
- [x] Listen for 'submit' event on button and:
    - [x] Store selected agents into agentComps array
    - [x] Add the nextEntryId to the object.
    - [x] Increment the nextEntryId on the data model.
    - [x] Reset the comp selector box
- [x] Ensure that the page is mobile-responsive
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Verify that new entries are saved to local storage along with the rest of the data model on page reload.
- [x] Verify that each new entry receives an incrementing entryId.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
