### ISSUE TITLE
issue-4-view-comp-list

### ISSUE THREAD

**Issue by jeff-cruz** [jeff-cruz/valorant-comp-builder#4]
## 💰 Motivation

User can view their own list of comps.

## 📐 Plan

Create a list of user-generated team comps.

## 🖼️ Wireframes

![Screen Shot 2022-04-18 at 11 23 40 AM](https://user-images.githubusercontent.com/99565410/163855526-d71c7ab5-905e-49af-9f9a-2e2e1fedd005.png)
![Screen Shot 2022-04-18 at 11 24 38 AM](https://user-images.githubusercontent.com/99565410/163855636-3401364f-69af-4215-86f6-98de24b40e76.png)

## ✅ Task List
- [x] Create HTML & CSS to view list of team comp entries
- [x] Create an a tag in header named Comps to view team comp entries list
- [x] If there are no entries, display "no entries recorded" 
- [x] If there are entries:
  - [x] Create a function that renders a DOM tree for your entries display
  - [x] Get src urls from data.agentCompList 
  - [x] SetAttribute of img in DOM tree with 'src' and 'data.agentComplist.firstAgent' and repeat until all img have src attributes
  - [x] Ensure that all pictures in DOM tree are being displayed
- [x] Ensure that the page is mobile-responsive
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Verify that new entries are saved to local storage along with the rest of the data model on page reload.
- [x] Verify that each new entry receives an incrementing entryId.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
