### ISSUE TITLE
issue-5-delete-comp

### ISSUE THREAD

**Issue by jeff-cruz** [jeff-cruz/valorant-comp-builder#5]
## 💰 Motivation

User can delete a team comp from their comp list.

## 📐 Plan

Create a delete button that deletes the team comp from the list.

## 🖼️ Wireframes

![Screen Shot 2022-04-18 at 11 28 28 AM](https://user-images.githubusercontent.com/99565410/163856200-ce000896-78fa-4a03-b3e9-2f5b977c9e84.png)
![Screen Shot 2022-04-18 at 11 27 25 AM](https://user-images.githubusercontent.com/99565410/163856210-9079a9c3-7d67-46a5-8017-8eb6cc15ad5a.png)

## ✅ Task List
- [x] Add a delete button next to each entry
- [x] Create a modal for the delete pop up asking the user if they are sure they want to delete
- [x] On the modal pop up, create a cancel and delete button
- [x] Listen for a click on the delete button to show modal
    - [x] If user clicks cancel, hide modal and show entry list
    - [x] If user clicks delete, remove entry from entry list
- [x] Ensure that the page is mobile-responsive
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
